// Package api_docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package api_docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://domain.com",
        "contact": {
            "name": "Support",
            "url": "https://domain.com",
            "email": "contact@domain.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "description": "health check",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "/api/health",
                "responses": {
                    "200": {
                        "description": "server unix time",
                        "schema": {
                            "$ref": "#/definitions/api.MSG_RESP_HEALTH"
                        }
                    }
                }
            }
        },
        "/api/user/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "creat user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "creat user",
                "parameters": [
                    {
                        "description": "new user info",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.MSG_REQ_CREATE_USER"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.MSG_RESP_CREATE_USER"
                        }
                    }
                }
            }
        },
        "/api/user/get/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.MSG_RESP_GET_USER"
                        }
                    }
                }
            }
        },
        "/api/user/update": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "update user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "update user",
                "parameters": [
                    {
                        "description": "update user info",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.MSG_REQ_UPDATE_USER"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.MSG_RESP_UPDATE_USER"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.MSG_REQ_CREATE_USER": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.MSG_REQ_UPDATE_USER": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.MSG_RESP_CREATE_USER": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.MSG_RESP_GET_USER": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.MSG_RESP_HEALTH": {
            "type": "object",
            "properties": {
                "unixtime": {
                    "type": "integer"
                }
            }
        },
        "api.MSG_RESP_UPDATE_USER": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "api example",
	Description:      "api example",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
