definitions:
  api.MSG_REQ_CREATE_USER:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  api.MSG_REQ_UPDATE_USER:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        type: string
    type: object
  api.MSG_RESP_CREATE_USER:
    properties:
      email:
        type: string
      meta_message:
        type: string
      meta_status:
        type: integer
      name:
        type: string
    type: object
  api.MSG_RESP_GET_USER:
    properties:
      email:
        type: string
      meta_message:
        type: string
      meta_status:
        type: integer
      name:
        type: string
    type: object
  api.MSG_RESP_HEALTH:
    properties:
      unixtime:
        type: integer
    type: object
  api.MSG_RESP_UPDATE_USER:
    properties:
      email:
        type: string
      meta_message:
        type: string
      meta_status:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: contact@domain.com
    name: Support
    url: https://domain.com
  description: api example
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://domain.com
  title: api example
  version: "1.0"
paths:
  /api/health:
    get:
      description: health check
      produces:
      - application/json
      responses:
        "200":
          description: server unix time
          schema:
            $ref: '#/definitions/api.MSG_RESP_HEALTH'
      summary: /api/health
      tags:
      - health
  /api/user/create:
    post:
      consumes:
      - application/json
      description: creat user
      parameters:
      - description: new user info
        in: body
        name: msg
        required: true
        schema:
          $ref: '#/definitions/api.MSG_REQ_CREATE_USER'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/api.MSG_RESP_CREATE_USER'
      security:
      - ApiKeyAuth: []
      summary: creat user
      tags:
      - user
  /api/user/get/{id}:
    get:
      description: get user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/api.MSG_RESP_GET_USER'
      security:
      - ApiKeyAuth: []
      summary: get user
      tags:
      - user
  /api/user/update:
    post:
      consumes:
      - application/json
      description: update user
      parameters:
      - description: update user info
        in: body
        name: msg
        required: true
        schema:
          $ref: '#/definitions/api.MSG_REQ_UPDATE_USER'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/api.MSG_RESP_UPDATE_USER'
      security:
      - ApiKeyAuth: []
      summary: update user
      tags:
      - user
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
