default:
  daemon_name: cli-template-service
dev:
  auto_cert:
    check_interval: 3600
    crt_path: ""
    init_download: true
    key_path: ""
    url: ""
  db:
    host: localhost
    name: xxxx
    password: xxxxx
    port: 3306
    username: xxxx
  elasticsearch:
    host: xxxx
    password: xxxx
    username: xxxx
  http:
    enable: true
    html_dir: ""
    port: 88
  https:
    crt_path: assets/cert/crt.crt
    enable: true
    html_dir: assets/html
    key_path: assets/cert/key.key
    port: 443
  ip_geo:
    ip2l:
      db_path: assets/ip2l/IP2LOCATION-LITE-DB1.BIN
      upgrade_interval: 172800
      upgrade_url: ""
    ipstack_key: ""
    redis:
      host: ""
      password: ""
      port: 6379
      prefix: 'core:ipgeo:'
      use_tls: true
      username: ipgeoCore
  leveldb:
    path: ""
  log_level: INFO
  redis:
    host: 127.0.0.1
    password: ""
    port: 6379
    prefix: template
    use_tls: true
    username: ""
  smtp:
    host: ""
    password: ""
    port: 587
    username: ""
  sqlite:
    path: ""
mode: pro
pro:
  auto_cert:
    check_interval: 3600
    crt_path: ""
    init_download: true
    key_path: ""
    url: ""
  db:
    host: localhost
    name: xxxx
    password: xxxxx
    port: 3306
    username: xxxx
  elasticsearch:
    host: xxxx
    password: xxxx
    username: xxxx
  http:
    enable: true
    html_dir: ""
    port: 80
  https:
    crt_path: assets/cert/crt.crt
    enable: true
    html_dir: assets/html
    key_path: assets/cert/key.key
    port: 443
  ip_geo:
    ip2l:
      db_path: assets/ip2l/IP2LOCATION-LITE-DB1.BIN
      upgrade_interval: 172800
      upgrade_url: ""
    ipstack_key: ""
    redis:
      host: ""
      password: ""
      port: 6379
      prefix: 'core:ipgeo:'
      use_tls: true
      username: ipgeoCore
  log_level: INFO
  redis:
    host: 127.0.0.1
    password: ""
    port: 6379
    prefix: template
    use_tls: true
    username: ""
  smtp:
    host: ""
    password: ""
    port: 587
    username: ""
